<?php
include_once("assets/php/funkcije.php");
$ans = "";
?>
<!doctype html>
<html lang="sr">
    <head>
        <!-- meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="robots" content="Index, Follow">
        <meta name="keywords" content="">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="copyright" content="">
        <meta name="Audience" content="all">
        <meta name="distribution" content="global">
        <meta name="theme-color" content="#EBEBEB" >
        <meta name="language" content="sr">

        <link rel="preload" as="image" href="important.png">

        <link href="" rel="canonical">

        <link href="" rel="icon">
        <link href="" rel="apple-touch-icon">

        <title>Hello, world!</title>

        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon">

        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link href="css/style.css" rel="stylesheet">

        <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    </head>
    <body>
        <div class="container-fluid">

            <div class="row">
                <?php include_once("assets/php/navigacija.php"); ?>
            </div>

            <div class="row">
                <div class="col-12 text-center">
                    <?php echo $ans; ?>
                </div>
            </div>

            <div class="row">
                <?php include_once("assets/php/footer.php"); ?>
            </div>

        </div>

        <!-- JavaScript Libraries -->
        <script src="js/jquery-3.4.1.min.js"></script>
        <script src="js/bootstrap.bundle.min.js"></script>
        <script src="lib/chart/chart.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/waypoints/waypoints.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="lib/tempusdominus/js/moment.min.js"></script>
        <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
        <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

        <!-- Template Javascript -->
        <script src="js/main.js"></script>
    </body>
</html>